// src/templates/xlsx/customers-template.ts
import type { XlsxTemplateConfig } from "./types";

export const customersTemplate: XlsxTemplateConfig = {
  entity: "customers",
  sheetName: "Clientes",
  columns: [
    {
      key: "first_name",
      header: "Nombre",
      required: true,
      type: "string",
      description: "Nombre del cliente (obligatorio)",
      width: 20,
    },
    {
      key: "last_name",
      header: "Apellido",
      required: true,
      type: "string",
      description: "Apellido del cliente (obligatorio)",
      width: 20,
    },
    {
      key: "email",
      header: "Email",
      required: false,
      type: "string",
      description: "Correo electrónico",
      width: 30,
    },
    {
      key: "phone",
      header: "Teléfono",
      required: false,
      type: "string",
      description: "Número de teléfono",
      width: 18,
    },
    {
      key: "phone_country_code",
      header: "Código país",
      required: false,
      type: "string",
      defaultValue: "+58",
      description: "Código de país (ej: +58, +1)",
      width: 12,
    },
    {
      key: "document_type",
      header: "Tipo documento",
      required: false,
      type: "string",
      description: "Tipo de documento (ej: V, E, J, P)",
      width: 15,
    },
    {
      key: "document_number",
      header: "Nro. documento",
      required: false,
      type: "string",
      description: "Número de documento de identidad",
      width: 18,
    },
    {
      key: "birth_date",
      header: "Fecha nacimiento",
      required: false,
      type: "date",
      description: "Formato: YYYY-MM-DD (ej: 1990-05-15)",
      width: 18,
    },
    {
      key: "gender",
      header: "Género",
      required: false,
      type: "enum",
      enumValues: ["male", "female", "other"],
      description: "male, female, other",
      width: 12,
    },
    {
      key: "address",
      header: "Dirección",
      required: false,
      type: "string",
      description: "Dirección del cliente",
      width: 35,
    },
    {
      key: "city",
      header: "Ciudad",
      required: false,
      type: "string",
      description: "Ciudad de residencia",
      width: 18,
    },
    {
      key: "tags",
      header: "Etiquetas",
      required: false,
      type: "string",
      description: "Separadas por coma (ej: VIP, frecuente)",
      width: 25,
    },
    {
      key: "notes",
      header: "Notas",
      required: false,
      type: "string",
      description: "Notas adicionales sobre el cliente",
      width: 35,
    },
  ],
};
