// src/templates/xlsx/products-template.ts
import type { XlsxTemplateConfig } from "./types";

export const productsTemplate: XlsxTemplateConfig = {
  entity: "products",
  sheetName: "Productos",
  columns: [
    {
      key: "name",
      header: "Nombre",
      required: true,
      type: "string",
      description: "Nombre del producto (obligatorio)",
      width: 28,
    },
    {
      key: "price",
      header: "Precio",
      required: true,
      type: "number",
      description: "Precio de venta (obligatorio, ej: 12.50)",
      width: 12,
    },
    {
      key: "currency_iso",
      header: "Moneda",
      required: false,
      type: "string",
      defaultValue: "USD",
      description: "Código ISO de la moneda (ej: USD, BOB)",
      width: 10,
    },
    {
      key: "sku",
      header: "SKU",
      required: false,
      type: "string",
      description: "Código único del producto",
      width: 14,
    },
    {
      key: "category",
      header: "Categoría",
      required: false,
      type: "string",
      description: "Categoría del producto",
      width: 18,
    },
    {
      key: "brand",
      header: "Marca",
      required: false,
      type: "string",
      description: "Marca del producto",
      width: 16,
    },
    {
      key: "stock_quantity",
      header: "Stock inicial",
      required: false,
      type: "number",
      defaultValue: 0,
      description: "Unidades iniciales (movimiento de entrada)",
      width: 14,
    },
    {
      key: "min_stock_alert",
      header: "Alerta mínima",
      required: false,
      type: "number",
      defaultValue: 0,
      description: "Stock mínimo antes de alertar",
      width: 14,
    },
    {
      key: "branch",
      header: "Sucursal",
      required: false,
      type: "string",
      description: "Nombre de la sucursal (vacío = principal)",
      width: 20,
    },
    {
      key: "is_active",
      header: "Activo",
      required: false,
      type: "boolean",
      defaultValue: true,
      description: "true o false",
      width: 10,
    },
    {
      key: "description",
      header: "Descripción",
      required: false,
      type: "string",
      description: "Descripción del producto",
      width: 35,
    },
  ],
};
