// src/templates/xlsx/services-template.ts
import type { XlsxTemplateConfig } from "./types";

export const servicesTemplate: XlsxTemplateConfig = {
  entity: "services",
  sheetName: "Servicios",
  columns: [
    {
      key: "name",
      header: "Nombre",
      required: true,
      type: "string",
      description: "Nombre del servicio (obligatorio)",
      width: 30,
    },
    {
      key: "category",
      header: "Categoría",
      required: true,
      type: "enum",
      enumValues: ["hair", "nails", "skin", "makeup", "spa", "barber", "other"],
      description: "hair, nails, skin, makeup, spa, barber, other",
      width: 15,
    },
    {
      key: "duration_minutes",
      header: "Duración (min)",
      required: true,
      type: "number",
      description: "Duración en minutos (5-480)",
      width: 15,
    },
    {
      key: "base_price",
      header: "Precio base",
      required: true,
      type: "number",
      description: "Precio base del servicio",
      width: 15,
    },
    {
      key: "description",
      header: "Descripción",
      required: false,
      type: "string",
      description: "Descripción opcional del servicio",
      width: 40,
    },
    {
      key: "buffer_minutes",
      header: "Buffer (min)",
      required: false,
      type: "number",
      defaultValue: 0,
      description: "Minutos de descanso entre citas (0-60)",
      width: 12,
    },
    {
      key: "currency_code",
      header: "Moneda",
      required: false,
      type: "string",
      defaultValue: "USD",
      description: "Código de moneda (ej: USD, EUR)",
      width: 10,
    },
    {
      key: "requires_specialist",
      header: "Requiere especialista",
      required: false,
      type: "boolean",
      defaultValue: true,
      description: "true o false",
      width: 20,
    },
    {
      key: "requires_station",
      header: "Requiere estación",
      required: false,
      type: "boolean",
      defaultValue: false,
      description: "true o false",
      width: 18,
    },
    {
      key: "is_featured",
      header: "Destacado",
      required: false,
      type: "boolean",
      defaultValue: false,
      description: "true o false",
      width: 12,
    },
    {
      key: "is_active",
      header: "Activo",
      required: false,
      type: "boolean",
      defaultValue: true,
      description: "true o false",
      width: 10,
    },
  ],
};
