// src/templates/xlsx/specialists-template.ts
import type { XlsxTemplateConfig } from "./types";

export const specialistsTemplate: XlsxTemplateConfig = {
  entity: "specialists",
  sheetName: "Especialistas",
  columns: [
    {
      key: "full_name",
      header: "Nombre completo",
      required: true,
      type: "string",
      description: "Nombre completo del especialista (obligatorio)",
      width: 30,
    },
    {
      key: "email",
      header: "Email",
      required: true,
      type: "string",
      description: "Correo electrónico (obligatorio, único)",
      width: 30,
    },
    {
      key: "phone",
      header: "Teléfono",
      required: false,
      type: "string",
      description: "Número de teléfono",
      width: 18,
    },
    {
      key: "role",
      header: "Rol",
      required: false,
      type: "enum",
      enumValues: ["owner", "admin", "manager", "employee"],
      defaultValue: "employee",
      description: "owner, admin, manager, employee",
      width: 15,
    },
    {
      key: "specialties",
      header: "Especialidades",
      required: false,
      type: "string",
      description: "Separadas por coma (ej: hair_cutting, nails_manicure)",
      width: 35,
    },
    {
      key: "bio",
      header: "Biografía",
      required: false,
      type: "string",
      description: "Descripción breve del especialista",
      width: 40,
    },
    {
      key: "commission_type",
      header: "Tipo comisión",
      required: false,
      type: "enum",
      enumValues: ["percentage", "fixed", "mixed"],
      description: "percentage, fixed, mixed",
      width: 15,
    },
    {
      key: "commission_percentage",
      header: "Comisión %",
      required: false,
      type: "number",
      description: "Porcentaje de comisión (0-100)",
      width: 12,
    },
    {
      key: "commission_fixed",
      header: "Comisión fija",
      required: false,
      type: "number",
      description: "Monto fijo de comisión",
      width: 14,
    },
    {
      key: "is_active",
      header: "Activo",
      required: false,
      type: "boolean",
      defaultValue: true,
      description: "true o false",
      width: 10,
    },
  ],
};
